# Generated by Django 3.0.5 on 2021-05-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisor_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='advisor_photo_url',
            field=models.URLField(),
        ),
    ]
